/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.MenuComponent;
import java.awt.Window;
import javax.swing.JLabel;

/**
 *
 * @author Pavel
 */
public class Panel extends javax.swing.JFrame {
    
    CardLayout c;
    CardLayout timerContainerLayout;
    
    @SuppressWarnings("LeakingThisInConstructor")
    public Panel() {        
        initComponents();
        c = new CardLayout();
        timerContainerLayout = new CardLayout();
        Panel_Display.setLayout(c);
        panelTimerContainer.setLayout(timerContainerLayout);
        Refresh();
        
        //wątki zegar
        Zegar zegar = new Zegar();
        panelTimerContainer.add(zegar, "Timer");
        timerContainerLayout.show(panelTimerContainer, "Timer");
        zegar.start();
        

        //Times.add(zegar);
        //zegar.start();
        
        JLabel lab = new JLabel();
        lab.setText("test");
        //Times.add(lab);
        
        
    }
    
    public void Refresh(){
        Panel_Display.removeAll();
        
        Panel_Main main = new Panel_Main();
        Panel_Display.add(main,"Main");
        
        Panel_N_Klient klient = new Panel_N_Klient();
        Panel_Display.add(klient, "N_Klient");
        
         Panel_N_Mag mag = new  Panel_N_Mag();
        Panel_Display.add(mag, "N_Mag");
        
        Panel_S_Mag s_mag = new Panel_S_Mag();
        s_mag.ParentFrame = this;
        Panel_Display.add(s_mag, "S_Mag");
        
        Panel_S_Klient s_klient = new Panel_S_Klient();
        s_klient.ParentFrame = this;
        Panel_Display.add(s_klient,"S_Klient"); 
        
        Panel_S_Wyp wypoz = new Panel_S_Wyp();
        wypoz.ParentFrame = this;
        Panel_Display.add(wypoz,"Wypoz");
        
        Panel_N_Wyp u_wyp = new Panel_N_Wyp();
        Panel_Display.add(u_wyp,"U_Wyp");
        
        Panel_Wyp_Search wyp_search = new Panel_Wyp_Search();
        Panel_Display.add(wyp_search,"Wyp_Search");
        
        Panel_Plik plik = new Panel_Plik();
        Panel_Display.add(plik,"Plik");
    }
    
    public void Opened_E_Klient(String ID){
        DataContainer.ID_K = ID;
        Panel_E_Klient e_klient = new Panel_E_Klient();
        e_klient.ParentFrame = this;
        Panel_Display.add(e_klient, "E_Klient");
        c.show(Panel_Display, "E_Klient");
    }
     
    public void Opened_E_Mag(String ID){
        DataContainer.ID_M = ID;
        Panel_E_Mag e_mag = new Panel_E_Mag();
        e_mag.ParentPanel = this;
        Panel_Display.add(e_mag,"E_Mag");
        c.show(Panel_Display, "E_Mag");
    }
    
    public void Opened_E_Wyp(String ID){
        DataContainer.ID_W = ID;
        Panel_E_Wyp e_wyp = new Panel_E_Wyp();
        e_wyp.ParentFrame = this;
        Panel_Display.add(e_wyp,"E_wyp");
        c.show(Panel_Display,"E_wyp");
    }
    
     public void Opened_Z_Wyp(String ID){
        DataContainer.ID_W = ID;
        Panel_K_Wyp k_wyp = new Panel_K_Wyp();
        k_wyp.ParentFrame = this;
        Panel_Display.add(k_wyp,"K_wyp");
        c.show(Panel_Display,"K_wyp");
    }
    
    public void Opened_S_Klient(){
        //Panel_Display.validate();
        //Panel_Display.repaint();
        //Panel_Display.revalidate();
        //Panel_S_Klient.Load();
        
        Panel_S_Klient s_klient = new Panel_S_Klient();
        s_klient.ParentFrame = this;
        Panel_Display.add(s_klient,"S_Klient"); 
        c.show(Panel_Display, "S_Klient");
        MenuComponent e_klient = null;
        Panel_Display.remove(e_klient);        
        //super.validate();
        //Panel_Display.validate();
        //c.previous(Panel_Display);  
    }
    
    public void Opened_S_Wyp(){
        Panel_S_Wyp s_wyp = new Panel_S_Wyp();
        s_wyp.ParentFrame = this;
        Panel_Display.add(s_wyp,"S_wyp");
        c.show(Panel_Display,"S_wyp");
        MenuComponent k_wyp = null;
        MenuComponent e_wyp = null;
        Panel_Display.remove(e_wyp);
        Panel_Display.remove(k_wyp);
    }
    
    public void Opened_S_Mag(){
        //Panel_S_Mag.Load();
        Panel_S_Mag s_mag = new Panel_S_Mag();
        s_mag.ParentFrame = this;
        Panel_Display.add(s_mag, "S_Mag");
        c.show(Panel_Display,"S_Mag");
        MenuComponent e_mag = null;
        Panel_Display.remove(e_mag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Panel_N_K = new javax.swing.JPanel();
        L_imie = new javax.swing.JLabel();
        TF_imie = new javax.swing.JTextField();
        L_nazwisko = new javax.swing.JLabel();
        TF_nazwisko = new javax.swing.JTextField();
        L_ulica = new javax.swing.JLabel();
        TF_ulica = new javax.swing.JTextField();
        L_nr = new javax.swing.JLabel();
        TF_nr = new javax.swing.JTextField();
        L_kod = new javax.swing.JLabel();
        TF_kod = new javax.swing.JTextField();
        L_miasto = new javax.swing.JLabel();
        TF_miasto = new javax.swing.JTextField();
        B_save_new_K = new javax.swing.JButton();
        Panel_N_M = new javax.swing.JPanel();
        L_kategoria = new javax.swing.JLabel();
        CB_kategoria = new javax.swing.JComboBox();
        L_producent = new javax.swing.JLabel();
        TF_producent = new javax.swing.JTextField();
        L_nazwa = new javax.swing.JLabel();
        TF_nazwa = new javax.swing.JTextField();
        L_model = new javax.swing.JLabel();
        TF_model = new javax.swing.JTextField();
        L_opis = new javax.swing.JLabel();
        TF_opis = new javax.swing.JTextField();
        L_cena = new javax.swing.JLabel();
        TF_cena = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        B_N_Mag = new javax.swing.JButton();
        B_E_Mag = new javax.swing.JButton();
        B_N_Client = new javax.swing.JButton();
        B_E_Client = new javax.swing.JButton();
        B_Wyp = new javax.swing.JButton();
        Panel_Display = new javax.swing.JPanel();
        B_U_Wyp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelTimerContainer = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        Panel_N_K.setPreferredSize(new java.awt.Dimension(315, 208));

        L_imie.setText("Imię:");

        TF_imie.setMinimumSize(new java.awt.Dimension(6, 40));
        TF_imie.setPreferredSize(new java.awt.Dimension(50, 20));

        L_nazwisko.setText("Nazwisko: ");

        TF_nazwisko.setToolTipText("");
        TF_nazwisko.setPreferredSize(new java.awt.Dimension(50, 20));

        L_ulica.setText("Ulica:");

        L_nr.setText("nr: ");

        TF_nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nrActionPerformed(evt);
            }
        });

        L_kod.setText("Kod:");

        L_miasto.setText("Miasto: ");

        B_save_new_K.setText("Zapisz");
        B_save_new_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_save_new_KActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_N_KLayout = new javax.swing.GroupLayout(Panel_N_K);
        Panel_N_K.setLayout(Panel_N_KLayout);
        Panel_N_KLayout.setHorizontalGroup(
            Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_N_KLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_N_KLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B_save_new_K))
                    .addGroup(Panel_N_KLayout.createSequentialGroup()
                        .addComponent(L_miasto)
                        .addGap(18, 18, 18)
                        .addComponent(TF_miasto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_N_KLayout.createSequentialGroup()
                        .addComponent(L_imie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_N_KLayout.createSequentialGroup()
                        .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_N_KLayout.createSequentialGroup()
                                .addComponent(L_nazwisko)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_N_KLayout.createSequentialGroup()
                                .addComponent(L_ulica)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_N_KLayout.createSequentialGroup()
                                .addComponent(L_nr)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_N_KLayout.createSequentialGroup()
                                .addComponent(L_kod)
                                .addGap(34, 34, 34)))
                        .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_nazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_ulica)
                            .addComponent(TF_nr)
                            .addComponent(TF_kod))))
                .addContainerGap())
        );
        Panel_N_KLayout.setVerticalGroup(
            Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_N_KLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_imie)
                    .addComponent(TF_imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_N_KLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(L_nazwisko)))
                .addGap(6, 6, 6)
                .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_ulica)
                    .addComponent(TF_ulica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_nr)
                    .addComponent(TF_nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_kod)
                    .addComponent(TF_kod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Panel_N_KLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_miasto)
                    .addComponent(TF_miasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(B_save_new_K)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        L_kategoria.setText("Kategoria: ");

        CB_kategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        L_producent.setText("Producent:");

        TF_producent.setText("jTextField1");

        L_nazwa.setText("Nazwa:");

        TF_nazwa.setText("jTextField2");

        L_model.setText("Model:");

        TF_model.setText("jTextField3");

        L_opis.setText("Opis:");

        TF_opis.setText("jTextField4");

        L_cena.setText("Cena:");

        TF_cena.setText("jTextField5");

        jButton1.setText("Zapisz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_N_MLayout = new javax.swing.GroupLayout(Panel_N_M);
        Panel_N_M.setLayout(Panel_N_MLayout);
        Panel_N_MLayout.setHorizontalGroup(
            Panel_N_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_N_MLayout.createSequentialGroup()
                .addGroup(Panel_N_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_N_MLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addGroup(Panel_N_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_N_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(L_producent, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(L_nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(L_model, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(L_opis)
                                .addComponent(L_cena, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_N_MLayout.createSequentialGroup()
                                    .addGroup(Panel_N_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TF_cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(Panel_N_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TF_nazwa)
                                            .addComponent(TF_producent)
                                            .addComponent(TF_model)
                                            .addComponent(TF_opis))
                                        .addComponent(CB_kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)))
                            .addComponent(L_kategoria)))
                    .addGroup(Panel_N_MLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addGap(2, 2, 2))
        );
        Panel_N_MLayout.setVerticalGroup(
            Panel_N_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_N_MLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(CB_kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_producent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(TF_opis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_producent, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_nazwa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_model)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_opis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_cena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_kategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wypożyczalnia Sprzętu Sportowych");
        setMinimumSize(new java.awt.Dimension(800, 600));

        B_N_Mag.setText("Dodaj Magazyn");
        B_N_Mag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N_MagActionPerformed(evt);
            }
        });

        B_E_Mag.setText("Stan Magazyn");
        B_E_Mag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_E_MagActionPerformed(evt);
            }
        });

        B_N_Client.setText("Dodaj Klient");
        B_N_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N_ClientActionPerformed(evt);
            }
        });

        B_E_Client.setText("Stan Klient");
        B_E_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_E_ClientActionPerformed(evt);
            }
        });

        B_Wyp.setText("Stan Wypożyczenia");
        B_Wyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_WypActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_DisplayLayout = new javax.swing.GroupLayout(Panel_Display);
        Panel_Display.setLayout(Panel_DisplayLayout);
        Panel_DisplayLayout.setHorizontalGroup(
            Panel_DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        Panel_DisplayLayout.setVerticalGroup(
            Panel_DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        B_U_Wyp.setText("Utwórz Wypożyczenia");
        B_U_Wyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_U_WypActionPerformed(evt);
            }
        });

        jButton2.setText("Szuka Klienta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Plik");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Odśwież");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        panelTimerContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout panelTimerContainerLayout = new javax.swing.GroupLayout(panelTimerContainer);
        panelTimerContainer.setLayout(panelTimerContainerLayout);
        panelTimerContainerLayout.setHorizontalGroup(
            panelTimerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelTimerContainerLayout.setVerticalGroup(
            panelTimerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_N_Mag)
                    .addComponent(B_E_Mag)
                    .addComponent(B_N_Client)
                    .addComponent(B_E_Client)
                    .addComponent(B_Wyp)
                    .addComponent(B_U_Wyp)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTimerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_N_Mag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_E_Mag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_N_Client)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_E_Client)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_Wyp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_U_Wyp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelTimerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panel_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_N_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N_ClientActionPerformed
        c.show(Panel_Display, "N_Klient");
        //this.Panel_Main.add(N_Klient);
        //this.Panel_Main.getLayout().addLayoutComponent(N_Klient, Panel_Main);
        //this.Panel_Main.getLayout().layoutContainer(Panel_N_Klient);
        //Panel_N_Klient pnk = new Panel_N_Klient();
        //this.Panel_Main.getLayout().layoutContainer(pnk);
        //((CardLayout)this.Panel_Display.getLayout()).show(Panel_Display, pnk.toString());
    }//GEN-LAST:event_B_N_ClientActionPerformed

    private void B_E_MagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_E_MagActionPerformed
        c.show(Panel_Display, "S_Mag");
    }//GEN-LAST:event_B_E_MagActionPerformed

    private void TF_nrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nrActionPerformed

    }//GEN-LAST:event_TF_nrActionPerformed

    private void B_save_new_KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_save_new_KActionPerformed

    }//GEN-LAST:event_B_save_new_KActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_E_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_E_ClientActionPerformed
        c.show(Panel_Display,"S_Klient");
    }//GEN-LAST:event_B_E_ClientActionPerformed

    private void B_WypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_WypActionPerformed
        c.show(Panel_Display,"Wypoz");
    }//GEN-LAST:event_B_WypActionPerformed

    private void B_U_WypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_U_WypActionPerformed
        c.show(Panel_Display,"U_Wyp");
    }//GEN-LAST:event_B_U_WypActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        c.show(Panel_Display,"Wyp_Search");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        c.show(Panel_Display,"Plik");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void B_N_MagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N_MagActionPerformed
        c.show(Panel_Display, "N_Mag");

        //this.Panel_Main.getLayout().layoutContainer(Panel_N_Mag);
        //Panel_N_Mag pnm = new Panel_N_Mag();
        //((CardLayout)this.Panel_Display.getLayout()).show(Panel_Display, pnm.toString());
        //((CardLayout)this.Panel_Main.getLayout()).show(Panel_Main, "Panel_N_M" );
        //((CardLayout)this.Panel_Display.getLayout()).show(Panel_Display, "Panel_N_M");

    }//GEN-LAST:event_B_N_MagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_E_Client;
    private javax.swing.JButton B_E_Mag;
    private javax.swing.JButton B_N_Client;
    private javax.swing.JButton B_N_Mag;
    private javax.swing.JButton B_U_Wyp;
    private javax.swing.JButton B_Wyp;
    private javax.swing.JButton B_save_new_K;
    private javax.swing.JComboBox CB_kategoria;
    private javax.swing.JLabel L_cena;
    private javax.swing.JLabel L_imie;
    private javax.swing.JLabel L_kategoria;
    private javax.swing.JLabel L_kod;
    private javax.swing.JLabel L_miasto;
    private javax.swing.JLabel L_model;
    private javax.swing.JLabel L_nazwa;
    private javax.swing.JLabel L_nazwisko;
    private javax.swing.JLabel L_nr;
    private javax.swing.JLabel L_opis;
    private javax.swing.JLabel L_producent;
    private javax.swing.JLabel L_ulica;
    private javax.swing.JPanel Panel_Display;
    private javax.swing.JPanel Panel_N_K;
    private javax.swing.JPanel Panel_N_M;
    private javax.swing.JTextField TF_cena;
    private javax.swing.JTextField TF_imie;
    private javax.swing.JTextField TF_kod;
    private javax.swing.JTextField TF_miasto;
    private javax.swing.JTextField TF_model;
    private javax.swing.JTextField TF_nazwa;
    private javax.swing.JTextField TF_nazwisko;
    private javax.swing.JTextField TF_nr;
    private javax.swing.JTextField TF_opis;
    private javax.swing.JTextField TF_producent;
    private javax.swing.JTextField TF_ulica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel panelTimerContainer;
    // End of variables declaration//GEN-END:variables
}
