/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pavel
 */
public class Panel_N_Mag extends javax.swing.JPanel {
    private String[] args;

    /**
     * Creates new form Panel_N_Magazyn
     */
    public Panel_N_Mag() {
        initComponents();
        Hide();
        try {
            Baza();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_N_Mag.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }

    public void Hide(){
        L_S_kategoria.setVisible(false);
        L_S_producent.setVisible(false);
        L_S_nazwa.setVisible(false);
        L_S_model.setVisible(false);
        L_S_opis.setVisible(false);
        L_S_cena.setVisible(false);   
    }
    
    public void Clear(){
        CB_kategoria.setSelectedIndex(0);
        TF_producent.setText("");
        TF_nazwa.setText("");
        TF_model.setText("");
        TP_opis.setText("");
        TF_cena.setText("");
    }
    
    public void Baza() throws SQLException{
        Mysql sql = new Mysql();
        int n = sql.Tabel_row("kategorie");
        int c = sql.Tabel_col("kategorie");
        String baza[][] = new String[n][c];
        
        try{
            baza = sql.Kat_Stan();
            CB_kategoria.addItem("[wybierz]");
            for(int i =0;i<n;i++){
                CB_kategoria.addItem(baza[i][1]);
            }
         }catch(Exception e){
            e.printStackTrace();
            Plik p = new Plik();
            try {
                p.zapisPliku(e.toString());
            } catch (IOException ex) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_model = new javax.swing.JLabel();
        TF_model = new javax.swing.JTextField();
        L_opis = new javax.swing.JLabel();
        L_cena = new javax.swing.JLabel();
        L_kategoria = new javax.swing.JLabel();
        TF_cena = new javax.swing.JTextField();
        CB_kategoria = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        L_producent = new javax.swing.JLabel();
        TF_producent = new javax.swing.JTextField();
        L_nazwa = new javax.swing.JLabel();
        TF_nazwa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TP_opis = new javax.swing.JTextPane();
        L_S_kategoria = new javax.swing.JLabel();
        L_S_producent = new javax.swing.JLabel();
        L_S_nazwa = new javax.swing.JLabel();
        L_S_model = new javax.swing.JLabel();
        L_S_opis = new javax.swing.JLabel();
        L_S_cena = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 51, 51));

        L_model.setText("Model:");

        L_opis.setText("Opis:");

        L_cena.setText("Cena:");

        L_kategoria.setText("Kategoria: ");

        CB_kategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_kategoriaActionPerformed(evt);
            }
        });

        jButton1.setText("Zapisz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        L_producent.setText("Producent:");

        TF_producent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_producentActionPerformed(evt);
            }
        });

        L_nazwa.setText("Nazwa:");

        jScrollPane1.setViewportView(TP_opis);

        L_S_kategoria.setForeground(new java.awt.Color(255, 51, 51));
        L_S_kategoria.setText("Nie wybrano!!");

        L_S_producent.setForeground(new java.awt.Color(255, 51, 51));
        L_S_producent.setText("Brakuje pola!!");

        L_S_nazwa.setForeground(new java.awt.Color(255, 51, 51));
        L_S_nazwa.setText("Brakuje pola!!");

        L_S_model.setForeground(new java.awt.Color(255, 51, 51));
        L_S_model.setText("Brakuje pola!!");

        L_S_opis.setForeground(new java.awt.Color(255, 51, 51));
        L_S_opis.setText("Brakuje pola!!");

        L_S_cena.setForeground(new java.awt.Color(255, 51, 51));
        L_S_cena.setText("Brakuje pola!!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nowy Magazyn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_cena)
                                        .addGap(42, 42, 42)
                                        .addComponent(TF_cena))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(L_kategoria)
                                            .addGap(18, 18, 18)
                                            .addComponent(CB_kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(L_producent)
                                                .addComponent(L_nazwa)
                                                .addComponent(L_model)
                                                .addComponent(L_opis))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TF_nazwa)
                                                .addComponent(TF_model)
                                                .addComponent(TF_producent)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_S_kategoria)
                                    .addComponent(L_S_producent)
                                    .addComponent(L_S_nazwa)
                                    .addComponent(L_S_model)
                                    .addComponent(L_S_opis)
                                    .addComponent(L_S_cena)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_kategoria)
                    .addComponent(CB_kategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_kategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_producent)
                    .addComponent(TF_producent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_producent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_nazwa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TF_nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L_S_nazwa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_model)
                    .addComponent(TF_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_model))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_opis)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(L_S_opis)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_cena)
                    .addComponent(TF_cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_cena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n = 6;
        int spr[] = new int[n];
        if(!TF_producent.getText().equals("")){
            spr[0] = 1; 
            L_S_producent.setVisible(false);
        }else{
            spr[0] = 0;
            L_S_producent.setVisible(true);
        }
        System.out.println("producent: "+TF_producent.getText());
        
        if(!TF_nazwa.getText().equals("")){
            spr[1] = 1;
            L_S_nazwa.setVisible(false);
        }else{
            spr[1] = 0;
            L_S_nazwa.setVisible(true);
        }
        
        if(!TF_model.getText().equals("")){
            spr[2] = 1;
            L_S_model.setVisible(false);
        }else{
            spr[2] = 0;
            L_S_model.setVisible(true);
        }
        
        if(!TP_opis.getText().equals("")){
            spr[3] = 1;
            L_S_opis.setVisible(false);
        }else{
            spr[3]=0;
            L_S_opis.setVisible(true);
        }
        
        if(!TF_cena.getText().equals("")){
            spr[4] = 1;
            L_S_cena.setVisible(false);
        }else{
            spr[4] = 0;
            L_S_cena.setVisible(true);
        }
        System.out.println();
       
        if(CB_kategoria.getSelectedItem()!="[wybierz]"){
            spr[5] = 1;
            L_S_kategoria.setVisible(false);
        }else{
            spr[5] = 0;
            L_S_kategoria.setVisible(true);
        }
        
        int SUM=0;
        for(int i=0;i<n;i++){
            SUM +=spr[i];
        }
        if(SUM == n){
                Save_Baza(CB_kategoria.getSelectedIndex(), TF_producent.getText(), TF_nazwa.getText(), TF_model.getText(), TP_opis.getText(), TF_cena.getText());
                Frame_Save_Baza f = new Frame_Save_Baza();
                f.main(args);
                this.setVisible(false);
                Clear();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Save_Baza(int kat, String prod, String nazwa, String model, String opis, String cena){
        try {
            Mysql sql = new Mysql();
            sql.Mag_Add(kat, prod, nazwa, model, opis, cena);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_N_Mag.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
    
    private void TF_producentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_producentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_producentActionPerformed

    private void CB_kategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_kategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_kategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB_kategoria;
    private javax.swing.JLabel L_S_cena;
    private javax.swing.JLabel L_S_kategoria;
    private javax.swing.JLabel L_S_model;
    private javax.swing.JLabel L_S_nazwa;
    private javax.swing.JLabel L_S_opis;
    private javax.swing.JLabel L_S_producent;
    private javax.swing.JLabel L_cena;
    private javax.swing.JLabel L_kategoria;
    private javax.swing.JLabel L_model;
    private javax.swing.JLabel L_nazwa;
    private javax.swing.JLabel L_opis;
    private javax.swing.JLabel L_producent;
    private javax.swing.JTextField TF_cena;
    private javax.swing.JTextField TF_model;
    private javax.swing.JTextField TF_nazwa;
    private javax.swing.JTextField TF_producent;
    private javax.swing.JTextPane TP_opis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
