/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import static Main.Panel_N_Wyp.calculateDifference;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pavel
 */
public class Panel_E_Wyp extends javax.swing.JPanel {
    public Panel ParentFrame;
    String ID;
    String ID_M;
    Date Date_W;
    int er = 0;
    private String[] args;
    /**
     * Creates new form Panel_E_Wyp
     */
    public Panel_E_Wyp() {
        initComponents();
        error_date.setVisible(false);
        L_koszt.setVisible(false);
        Item();
        ID = DataContainer.ID_W;
        Baza();
    }
    
    public void Item(){
        JD_z.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            //@Override
            public void propertyChange(PropertyChangeEvent e) {
                if ("date".equals(e.getPropertyName())) {
                    //System.out.println((Date) e.getNewValue());
                    if(JD_z.getDate() != null && Date_W!= null){
                        if(Date_W.compareTo(JD_z.getDate())<0){
                            int dni = calculateDifference(Date_W,JD_z.getDate());
                            Search_ID_cen(dni, ID_M);
                            error_date.setVisible(false);
                            er = 0;
                        }else{
                            error_date.setVisible(true);
                            er = 1;
                        }                        
                    }
                }
            }
        });
    }
    
    public void Search_ID_cen(int dni, String ID){
        try {
            Mysql sql = new Mysql();
            String cena;
            cena = sql.Mag_Cena(ID);
            int cen = Integer.parseInt(cena);
            cen *= dni;
            L_koszt.setText("Koszt wypozyczalnia: "+cen+" złotych");
        } catch (SQLException ex) {
            Logger.getLogger(Panel_E_Wyp.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
    
    public void Save(){
        
    }
    
    public void Baza(){
        try {
            Mysql sql = new Mysql();
            String baza[] = new String[5];
            baza = sql.Wyp_Search(ID);
            ID_M = baza[2];
            
            String baza_k = new String();
            String baza_m = new String();
            baza_k = sql.Client_Search_Name(baza[1]);
            baza_m = sql.Mag_Search_Name(baza[2]);
            String dw = baza[3];
            String d_z = baza[4];
            SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
            Date_W = ft.parse(dw);
            Date dz = ft.parse(d_z);
            L_Klient.setText(baza_k);
            L_Mag.setText(baza_m);
            L_Dw.setText(dw);
            JD_z.setDate(dz);
            
        } catch (SQLException ex) {
            Logger.getLogger(Panel_E_Wyp.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Panel_E_Wyp.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        L_Klient = new javax.swing.JLabel();
        L_Mag = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        L_Dw = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JD_z = new com.toedter.calendar.JDateChooser();
        B_Save = new javax.swing.JButton();
        B_Exit = new javax.swing.JButton();
        error_date = new javax.swing.JLabel();
        L_koszt = new javax.swing.JLabel();

        jLabel1.setText("Klient:");

        jLabel2.setText("Magazyn:");

        L_Klient.setText("jLabel3");

        L_Mag.setText("jLabel3");

        jLabel5.setText("Data wypożu:");

        L_Dw.setText("jLabel3");

        jLabel7.setText("Data zwrotu:");

        B_Save.setText("Zapisz");
        B_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SaveActionPerformed(evt);
            }
        });

        B_Exit.setText("Anuluj");
        B_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ExitActionPerformed(evt);
            }
        });

        error_date.setForeground(new java.awt.Color(255, 0, 51));
        error_date.setText("Błąd datę");

        L_koszt.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(B_Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(B_Exit)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(L_Mag)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(L_Klient))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addComponent(L_Dw))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(JD_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(error_date))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(L_koszt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Klient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Mag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Dw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JD_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_date))
                .addGap(18, 18, 18)
                .addComponent(L_koszt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Save)
                    .addComponent(B_Exit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void B_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ExitActionPerformed
       ParentFrame.Opened_S_Wyp();
    }//GEN-LAST:event_B_ExitActionPerformed

    private void B_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SaveActionPerformed
        if(er == 0){
            Save();
        }else{
            Frame_Error_Save k = new Frame_Error_Save();
            k.main(args);
        }
    }//GEN-LAST:event_B_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Exit;
    private javax.swing.JButton B_Save;
    private com.toedter.calendar.JDateChooser JD_z;
    private javax.swing.JLabel L_Dw;
    private javax.swing.JLabel L_Klient;
    private javax.swing.JLabel L_Mag;
    private javax.swing.JLabel L_koszt;
    private javax.swing.JLabel error_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
