/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pavel
 */
public class Panel_K_Wyp extends javax.swing.JPanel {
    Panel ParentFrame;
    String ID;
    /**
     * Creates new form Panel_K_Wyp
     */
    public Panel_K_Wyp() {
        ID = DataContainer.ID_W;
        initComponents();
        Baza();
    }
    
    public void Delete(){
        try {
            Mysql sql = new Mysql();
            sql.Wyp_Delete(ID);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_K_Wyp.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        ParentFrame.Opened_S_Wyp();
    }   
    
    public void Baza(){
        try {
            Mysql sql = new Mysql();
            String baza[] = new String[5];
            baza = sql.Wyp_Search(ID);
            String baza_k = sql.Client_Search_Name(baza[1]);
            String baza_m = sql.Mag_Search_Name(baza[2]);
            String dw,dz;
            dw = baza[3];
            dz = baza[4];
            Date DW, DZ;
            SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
            DW = ft.parse(dw);
            DZ = ft.parse(dz);
            int day = calculateDifference(DW, DZ);
            String cena = sql.Mag_Cena(baza[2]);
            int cen = Integer.parseInt(cena);
            int koszt = cen*day;
            
            L_klient.setText(baza_k);
            L_mag.setText(baza_m);
            L_data.setText(dw+" - "+dz);
            L_czas.setText(day+" dni");
            L_koszt.setText(koszt+" złotych");
            
        } catch (SQLException ex) {
            Logger.getLogger(Panel_K_Wyp.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Panel_K_Wyp.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
    
    public static int calculateDifference(Date a, Date b){
        int tempDifference = 0;
        int difference = 0;
        Calendar earlier = Calendar.getInstance();
        Calendar later = Calendar.getInstance();
        
        if (a.compareTo(b) < 0){
            earlier.setTime(a);
            later.setTime(b);
        }else{
            earlier.setTime(b);
            later.setTime(a);
        }

        while (earlier.get(Calendar.YEAR) != later.get(Calendar.YEAR)){
            tempDifference = 365 * (later.get(Calendar.YEAR) - earlier.get(Calendar.YEAR));
            difference += tempDifference;

            earlier.add(Calendar.DAY_OF_YEAR, tempDifference);
        }

        if (earlier.get(Calendar.DAY_OF_YEAR) != later.get(Calendar.DAY_OF_YEAR)){
            tempDifference = later.get(Calendar.DAY_OF_YEAR) - earlier.get(Calendar.DAY_OF_YEAR);
            difference += tempDifference;

            earlier.add(Calendar.DAY_OF_YEAR, tempDifference);
        }

        return difference;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        L_klient = new javax.swing.JLabel();
        L_mag = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        L_data = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        L_czas = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        L_koszt = new javax.swing.JLabel();
        Returns = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        jLabel1.setText("Klient:");

        jLabel2.setText("Magazyn:");

        L_klient.setText("jLabel3");

        L_mag.setText("jLabel4");

        jLabel5.setText("Data:");

        L_data.setText("jLabel6");

        jLabel7.setText("Czas wypożu:");

        L_czas.setText("jLabel8");

        jLabel9.setText("Koszt wypożu:");

        L_koszt.setText("jLabel10");

        Returns.setText("Zwrotu");
        Returns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnsActionPerformed(evt);
            }
        });

        Exit.setText("Anuluj");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(L_mag)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(L_klient))
                                    .addComponent(jLabel2))
                                .addComponent(L_data)
                                .addComponent(L_czas)
                                .addComponent(L_koszt))
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(Returns)
                        .addGap(32, 32, 32)
                        .addComponent(Exit)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(L_klient)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_mag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_czas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_koszt)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Returns)
                    .addComponent(Exit))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnsActionPerformed
      Delete();
    }//GEN-LAST:event_ReturnsActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        ParentFrame.Opened_S_Wyp();
    }//GEN-LAST:event_ExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel L_czas;
    private javax.swing.JLabel L_data;
    private javax.swing.JLabel L_klient;
    private javax.swing.JLabel L_koszt;
    private javax.swing.JLabel L_mag;
    private javax.swing.JButton Returns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
