/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pavel
 */
public class Panel_Wyp_Search extends javax.swing.JPanel {
    
    /**
     * Creates new form Panel_Wyp_Search
     */
    public Panel_Wyp_Search() {
        initComponents();
        Baza();
    }
    
    public void Search(String ID){
        String pusty[] = new String[2];
        pusty[0] = "Pusty";
        try {
            Mysql sql = new Mysql();
            int n = sql.Wyp_Is_Klient(ID);
            if(n != 0){
                //JL_Klient_Mag.clearSelection();
                String Baza[][] = new String[sql.Tabel_row("wypoczalnia")][sql.Tabel_col("wypoczalnia")];
                Baza = sql.Wyp_Search_Klient_All(ID);
                String baza[] = new String[sql.Tabel_row("wypoczalnia")];
                for(int i=0;i<sql.Wyp_Is_Klient(ID);i++){
                    String mag = new String();

                    mag = sql.Mag_Search_Name(Baza[i][2]);
                    baza[i] = mag+" Data wypozu:"+Baza[i][3]+" Data zwrotu:"+Baza[i][4];
                }
                JL_Klient_Mag.setListData(baza);
            }else{
                JL_Klient_Mag.setListData(pusty);
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Wyp_Search.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
    
    public void Baza(){
        try {
            Mysql sql = new Mysql();
            String Baza[][] = new String[sql.Tabel_row("klient")][sql.Tabel_col("klient")];
            Baza = sql.Client_Stan();
            String baza[] = new String[sql.Tabel_row("klient")];
            for(int i=0;i<sql.Tabel_row("klient");i++){
                baza[i] = "ID:"+Baza[i][0]+" "+Baza[i][2]+" "+Baza[i][1];
            }
            JL_Klient.setListData(baza);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Wyp_Search.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Klient = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_Klient_Mag = new javax.swing.JList();

        JL_Klient.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JL_Klient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_KlientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JL_Klient);

        JL_Klient_Mag.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(JL_Klient_Mag);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JL_KlientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_KlientMouseClicked
        String value =(String) JL_Klient.getSelectedValue();
        int nr = JL_Klient.getSelectedIndex();
        if(nr != -1){
            Short_ID SID = new Short_ID();
            Search(SID.ID_K(value));
        }
    }//GEN-LAST:event_JL_KlientMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList JL_Klient;
    private javax.swing.JList JL_Klient_Mag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
