/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import java.awt.CardLayout;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Pavel
 */
public class Panel_N_Klient extends javax.swing.JPanel {
    private String[] args;

    /**
     * Creates new form Panel_N_Klient
     */
    public Panel_N_Klient() {
        initComponents();
        Hide();
    }
    
    public void Hide(){
        L_S_imie.setVisible(false);
        L_S_nazwisko.setVisible(false);
        L_S_ulica.setVisible(false);
        L_S_nr.setVisible(false);
        L_S_kod.setVisible(false);
        L_S_miasto.setVisible(false);
    }
    
    public void Clear(){
        TF_imie.setText("");
        TF_nazwisko.setText("");
        TF_ulica.setText("");
        TF_nr.setText("");
        TF_kod.setText("");
        TF_miasto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_imie = new javax.swing.JLabel();
        TF_imie = new javax.swing.JTextField();
        L_nazwisko = new javax.swing.JLabel();
        TF_nazwisko = new javax.swing.JTextField();
        L_ulica = new javax.swing.JLabel();
        TF_ulica = new javax.swing.JTextField();
        L_nr = new javax.swing.JLabel();
        TF_nr = new javax.swing.JTextField();
        L_kod = new javax.swing.JLabel();
        TF_kod = new javax.swing.JTextField();
        L_miasto = new javax.swing.JLabel();
        TF_miasto = new javax.swing.JTextField();
        B_save_new_K = new javax.swing.JButton();
        L_S_imie = new javax.swing.JLabel();
        L_S_nazwisko = new javax.swing.JLabel();
        L_S_ulica = new javax.swing.JLabel();
        L_S_nr = new javax.swing.JLabel();
        L_S_kod = new javax.swing.JLabel();
        L_S_miasto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(315, 208));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_imie.setText("Imię:");
        add(L_imie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        TF_imie.setMinimumSize(new java.awt.Dimension(6, 40));
        TF_imie.setPreferredSize(new java.awt.Dimension(40, 20));
        TF_imie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_imieActionPerformed(evt);
            }
        });
        add(TF_imie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 93, 25));

        L_nazwisko.setText("Nazwisko: ");
        add(L_nazwisko, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        TF_nazwisko.setToolTipText("");
        TF_nazwisko.setPreferredSize(new java.awt.Dimension(40, 20));
        TF_nazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nazwiskoActionPerformed(evt);
            }
        });
        add(TF_nazwisko, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 93, 25));

        L_ulica.setText("Ulica:");
        add(L_ulica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        add(TF_ulica, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 93, 25));

        L_nr.setText("nr: ");
        add(L_nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        TF_nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nrActionPerformed(evt);
            }
        });
        add(TF_nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 25));

        L_kod.setText("Kod:");
        add(L_kod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        add(TF_kod, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 93, 25));

        L_miasto.setText("Miasto: ");
        add(L_miasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        add(TF_miasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 92, 25));

        B_save_new_K.setText("Zapisz");
        B_save_new_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_save_new_KActionPerformed(evt);
            }
        });
        add(B_save_new_K, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        L_S_imie.setForeground(new java.awt.Color(255, 0, 51));
        L_S_imie.setText("Brakuje pola!!");
        add(L_S_imie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        L_S_nazwisko.setForeground(new java.awt.Color(255, 0, 51));
        L_S_nazwisko.setText("Brakuje pola!!");
        add(L_S_nazwisko, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        L_S_ulica.setForeground(new java.awt.Color(255, 0, 51));
        L_S_ulica.setText("Brakuje pola!!");
        add(L_S_ulica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        L_S_nr.setForeground(new java.awt.Color(255, 0, 51));
        L_S_nr.setText("Brakuje pola!!");
        add(L_S_nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        L_S_kod.setForeground(new java.awt.Color(255, 0, 51));
        L_S_kod.setText("Brakuje pola!!");
        add(L_S_kod, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        L_S_miasto.setForeground(new java.awt.Color(255, 0, 51));
        L_S_miasto.setText("Brakuje pola!!");
        add(L_S_miasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nowy Klient");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TF_nrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nrActionPerformed

    }//GEN-LAST:event_TF_nrActionPerformed

    private void B_save_new_KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_save_new_KActionPerformed
        int n=6;
        int spr[] = new int[n];
        
        if(!TF_imie.getText().equals("")){
            spr[0] = 1;
            L_S_imie.setVisible(false);
        }else{
            spr[0] = 0;
            L_S_imie.setVisible(true);
        }
        
        if(!TF_nazwisko.getText().equals("")){
            spr[1] = 1;
            L_S_nazwisko.setVisible(false);
        }else{
            spr[1] = 0;
            L_S_nazwisko.setVisible(true);
        }
        
        if(!TF_ulica.getText().equals("")){
            spr[2] = 1;
            L_S_ulica.setVisible(false);
        }else{
            spr[2] = 0;
            L_S_ulica.setVisible(true);
        }
        
        if(!TF_nr.getText().equals("")){
            spr[3] = 1;
            L_S_nr.setVisible(false);
        }else{
            spr[3] = 0;
            L_S_nr.setVisible(true);
        }
        
        if(!TF_kod.getText().equals("")){
            spr[4] = 1;
            L_S_kod.setVisible(false);
        }else{
            spr[4] = 0;
            L_S_kod.setVisible(true);
        }
        
        if(!TF_miasto.getText().equals("")){
            spr[5] = 1;
            L_S_miasto.setVisible(false);
        }else{
            spr[5] = 0;
            L_S_miasto.setVisible(true);
        }
        
        int SUM =0;
        for(int i=0;i<n;i++){
            SUM += spr[i];
        }
        
        if(SUM == n){
                Save_Baza(TF_imie.getText(), TF_nazwisko.getText(), TF_ulica.getText(), TF_nr.getText(), TF_kod.getText(), TF_miasto.getText());
                Frame_Save_Baza k = new Frame_Save_Baza();
                k.main(args);
                this.setVisible(false);
                Clear();
        }
    }//GEN-LAST:event_B_save_new_KActionPerformed

    public void Save_Baza(String imie, String nazw, String ul, String nr, String kod, String city){
        try {
            Mysql sql = new Mysql();
            sql.Client_Add(imie, nazw, ul, nr, kod, city);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_N_Klient.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
    
    private void TF_imieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_imieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_imieActionPerformed

    private void TF_nazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nazwiskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nazwiskoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_save_new_K;
    private javax.swing.JLabel L_S_imie;
    private javax.swing.JLabel L_S_kod;
    private javax.swing.JLabel L_S_miasto;
    private javax.swing.JLabel L_S_nazwisko;
    private javax.swing.JLabel L_S_nr;
    private javax.swing.JLabel L_S_ulica;
    private javax.swing.JLabel L_imie;
    private javax.swing.JLabel L_kod;
    private javax.swing.JLabel L_miasto;
    private javax.swing.JLabel L_nazwisko;
    private javax.swing.JLabel L_nr;
    private javax.swing.JLabel L_ulica;
    private javax.swing.JTextField TF_imie;
    private javax.swing.JTextField TF_kod;
    private javax.swing.JTextField TF_miasto;
    private javax.swing.JTextField TF_nazwisko;
    private javax.swing.JTextField TF_nr;
    private javax.swing.JTextField TF_ulica;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
