/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pavel
 */
public class Panel_E_Mag extends javax.swing.JPanel {
    String ID;
    
    public Panel ParentPanel;  
    public Panel_E_Mag() {
        ID = DataContainer.ID_M;
        initComponents();
        Hide();
        Baza();
    }
    
    public void Hide(){
        L_S_producent.setVisible(false);
        L_S_nazwa.setVisible(false);
        L_S_model.setVisible(false);
        L_S_opis.setVisible(false);
        L_S_cena.setVisible(false);
    }
    
    public void Baza(){
        try {
            Mysql sql = new Mysql();
            String baza[] = new String[sql.Tabel_col("magazyn")];
            baza = sql.Mag_Search(ID);
            TF_E_producent.setText(baza[2]);
            TF_E_nazwa.setText(baza[3]);
            TF_E_model.setText(baza[4]);
            TF_E_cena.setText(baza[6]);
            TA_E_opis.setText(baza[5]);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_E_Mag.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_producent1 = new javax.swing.JLabel();
        L_nazwa1 = new javax.swing.JLabel();
        L_model1 = new javax.swing.JLabel();
        L_cena1 = new javax.swing.JLabel();
        L_opis1 = new javax.swing.JLabel();
        TF_E_producent = new javax.swing.JTextField();
        TF_E_nazwa = new javax.swing.JTextField();
        TF_E_model = new javax.swing.JTextField();
        TF_E_cena = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA_E_opis = new javax.swing.JTextArea();
        save_Mag = new javax.swing.JButton();
        exit_Mag = new javax.swing.JButton();
        L_S_producent = new javax.swing.JLabel();
        L_S_nazwa = new javax.swing.JLabel();
        L_S_model = new javax.swing.JLabel();
        L_S_opis = new javax.swing.JLabel();
        L_S_cena = new javax.swing.JLabel();

        L_producent1.setText("Producent:");

        L_nazwa1.setText("Nazwa:");

        L_model1.setText("Model:");

        L_cena1.setText("Cena:");

        L_opis1.setText("Opis:");

        TA_E_opis.setColumns(20);
        TA_E_opis.setRows(5);
        jScrollPane2.setViewportView(TA_E_opis);

        save_Mag.setText("Zapisz");
        save_Mag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_MagActionPerformed(evt);
            }
        });

        exit_Mag.setText("Anuluj");
        exit_Mag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_MagActionPerformed(evt);
            }
        });

        L_S_producent.setForeground(new java.awt.Color(255, 51, 51));
        L_S_producent.setText("Brakuje pola!!");

        L_S_nazwa.setForeground(new java.awt.Color(255, 51, 51));
        L_S_nazwa.setText("Brakuje pola!!");

        L_S_model.setForeground(new java.awt.Color(255, 51, 51));
        L_S_model.setText("Brakuje pola!!");

        L_S_opis.setForeground(new java.awt.Color(255, 51, 51));
        L_S_opis.setText("Brakuje pola!!");

        L_S_cena.setForeground(new java.awt.Color(255, 51, 51));
        L_S_cena.setText("Brakuje pola!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TF_E_producent)
                    .addComponent(TF_E_nazwa)
                    .addComponent(TF_E_model)
                    .addComponent(TF_E_cena)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_producent1)
                            .addComponent(L_nazwa1)
                            .addComponent(L_model1)
                            .addComponent(L_cena1)
                            .addComponent(L_opis1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(save_Mag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(exit_Mag)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_S_producent)
                    .addComponent(L_S_nazwa)
                    .addComponent(L_S_model)
                    .addComponent(L_S_opis)
                    .addComponent(L_S_cena))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_producent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_E_producent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_producent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_nazwa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_E_nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_nazwa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_model1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_E_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_model))
                .addGap(12, 12, 12)
                .addComponent(L_cena1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_E_cena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_S_cena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_opis1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L_S_opis)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit_Mag)
                    .addComponent(save_Mag))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void save_MagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_MagActionPerformed
        int n = 5;
        int spr[] = new int[n];
        int sum = 0;
        
        if(!TF_E_producent.getText().equals("")){
            spr[0]= 1;
            L_S_producent.setVisible(false);
        }else{
            spr[0] = 0;
            L_S_producent.setVisible(false);
        }
        
        if(!TF_E_nazwa.getText().equals("")){
            spr[1] = 1;
            L_S_nazwa.setVisible(false);
        }else{
            spr[1] = 0;
            L_S_nazwa.setVisible(true);
        }
        
        if(!TF_E_model.getText().equals("")){
            spr[2] = 1;
            L_S_model.setVisible(false);
        }else{
            spr[2] = 1;
            L_S_model.setVisible(true);
        }
        
        if(!TF_E_cena.getText().equals("")){
            spr[3] = 1;
            L_S_cena.setVisible(false);
        }else{
            spr[3] = 0;
            L_S_cena.setVisible(true);
        }
        
        if(!TA_E_opis.getText().equals("")){
            spr[4] = 1;
            L_S_opis.setVisible(false);
        }else{
            spr[4] = 0;
            L_S_opis.setVisible(true);
        }
        
        for(int i = 0;i<n;i++){
            sum +=spr[i];
        }
        
        if(sum ==n){
            Save_Baza(TF_E_producent.getText(), TF_E_nazwa.getText(), TF_E_model.getText(), TA_E_opis.getText(), TF_E_cena.getText()); 
            ParentPanel.Opened_S_Mag();
        }
        
    }//GEN-LAST:event_save_MagActionPerformed

    public void Save_Baza(String prod, String nazwa, String model, String opis, String cena){
        try {
            Mysql sql = new Mysql();
            sql.Mag_Edit(prod, nazwa, model, opis, cena, ID);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_E_Mag.class.getName()).log(Level.SEVERE, null, ex);
            Plik p = new Plik();
            try {
                p.zapisPliku(ex.toString());
            } catch (IOException ex1) {
                Logger.getLogger(Panel_E_Klient.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        
    }
    
    private void exit_MagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_MagActionPerformed
        ParentPanel.Opened_S_Mag();
    }//GEN-LAST:event_exit_MagActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_S_cena;
    private javax.swing.JLabel L_S_model;
    private javax.swing.JLabel L_S_nazwa;
    private javax.swing.JLabel L_S_opis;
    private javax.swing.JLabel L_S_producent;
    private javax.swing.JLabel L_cena1;
    private javax.swing.JLabel L_model1;
    private javax.swing.JLabel L_nazwa1;
    private javax.swing.JLabel L_opis1;
    private javax.swing.JLabel L_producent1;
    private javax.swing.JTextArea TA_E_opis;
    private javax.swing.JTextField TF_E_cena;
    private javax.swing.JTextField TF_E_model;
    private javax.swing.JTextField TF_E_nazwa;
    private javax.swing.JTextField TF_E_producent;
    private javax.swing.JButton exit_Mag;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton save_Mag;
    // End of variables declaration//GEN-END:variables
}
